server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.rolex.alphax: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  oauth2:
    client:
      id: 1a6642b4-622d-11eb-a707-00059a3c7a00
      secret: