spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: 1a6642b4-622d-11eb-a707-00059a3c7a00
            client-secret: 123
            client-authentiacation-method: basic
            authorization-grant-type: authorization_code
            scope: read,write
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: gitlab
            client-name: Gitlab
          alphax:
            client-id: 1a6642b4-622d-11eb-a707-00059a3c7a00
            client-secret: 123
            client-authentiacation-method: basic
            authorization-grant-type: authorization_code
            scope: read,write
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: alphax
            client-name: AlphaX
        provider:
          alphax:
            authorization-uri: http://auth-server.com:8082/oauth/authorize
            token-uri: http://auth-server.com:8082/oauth/token
            user-info-uri: http://resource-server.com:8081/users/info
            user-name-attribute: username
          gitlab:
            authorization-uri: http://auth-server.com:8082/oauth/authorize
            token-uri: http://auth-server.com:8082/oauth/token
            user-info-uri: http://resource-server.com:8081/users/info
            user-name-attribute: username
  thymeleaf:
    suffix: .html
    mode: HTML5
    cache: false
    prefix: classpath:/templates/