server:
  port: 8088
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    service1:
      path: /hello
      serviceId: order-service
    service2:
      path: /world
      serviceId: order-service
    service3:
      path: /hello/world
      serviceId: order-service
    service4:
      path: /hello/*/world
      serviceId: order-service
    service5:
      path: /hello/**/world
      serviceId: order-service
    service6:
      path: /hello/*/world/**
      serviceId: order-service
    service7:
      path: /hello/**/world/**
      serviceId: order-service
    service8:
      path: /test
      serviceId: order-service
    service9:
      path: /haha
      serviceId: order-service
    service10:
      path: /url_test
      url: http://cn.bing.com
  include-debug-header: true
  debug:
    request: true
management:
  endpoints:
    web:
      exposure:
        include: '*'