spring:
  datasource:
    ds1:
      name: ds1
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
    ds2:
      name: ds2
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db2?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
    ds3:
      name: ds3
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db3?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
    ds4:
      name: ds4
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db4?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml